WheelWander/Controllers/BikesController.cs
using System.Dynamic;
using System.Security.Cryptography.Pkcs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WheelWander.Repositories;
using WheelWander.Consts;
using WheelWander.Models;
using WheelWander.ViewModels.Bikes;

namespace WheelWander.Controllers;
[Authorize(Roles = "Admin")]
public class BikesController :Controller
{
    private readonly IUnitOfWork _unitOfWork;

    public BikesController(IUnitOfWork unitOfWork)
    {
        this._unitOfWork = unitOfWork;
    }

    [HttpGet("/bikes")]
    public IActionResult List()
    {
        dynamic model = new ExpandoObject();
        model.Bikes = _unitOfWork.Bikes
            .FindAll(b => b.Status == Status.Active || b.Status == Status.Maintenance,
                new[] { "CurrentStation" });
        model.Locks = _unitOfWork.Locks
            .FindAll(l => l.Status == Status.Active || l.Status == Status.Maintenance,
                new[] { "Bike" });
        
        return View("../Dashboard/Bikes", new BikesViewModel(model));
    }

    [HttpGet("/bikes/{id}")]

    public IActionResult GetById(string id)
    {
        var bike = _unitOfWork.Bikes.Find(b => b.Id == id, new []{"CurrentStation"});
        var stations = _unitOfWork.Stations.GetAll().ToList();
        return View("../Dashboard/BikeDetails", new BikeViewModel(bike, stations));
    }
    [HttpPost("/bikes/update")]
    public IActionResult Update(CreateUpdateBikeViewModel bike)
    {
       // return Json(ModelState); 
        if (ModelState.IsValid)
        {
            _unitOfWork.Bikes.Update(new Bike()
            {
                Id = bike.Id,
                Status = bike.status,
                CurrentStationId = bike.currentStationId,
                BikeNumber = bike.bikeNumber
              
            });
            _unitOfWork.Complete();
        }

        return RedirectToAction(nameof(List));
    }
}

WheelWander/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WheelWander.Consts;
using WheelWander.Repositories;

namespace WheelWander.Controllers
{
    [Authorize(Roles = "Admin")]
    public class DashboardController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public DashboardController(IUnitOfWork unitOfWork)
        {
            this._unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Users()
        {
            return View();
        }

        public IActionResult Rentals()
        {
            var rentals = _unitOfWork.Rentals
                .FindAll(r => r.Status == Status.Active || r.Status == Status.Completed,
                    new[] { "Bike", "User", "StartStation", "EndStation" });
            return View(rentals);
        }
        
    }
}

WheelWander/Controllers/StationsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NetTopologySuite.Geometries;
using WheelWander.Consts;
using WheelWander.Models;
using WheelWander.Repositories;
using WheelWander.ViewModels.Stations;

namespace WheelWander.Controllers;

[Authorize(Roles = "Admin")]
public class StationsController : Controller
{
    private readonly IUnitOfWork _unitOfWork;

    public StationsController(IUnitOfWork unitOfWork)
    {
        _unitOfWork = unitOfWork;
    }

    [HttpGet("/stations")]
    public IActionResult GetAll()
    {
        var stations = _unitOfWork.Stations
            .FindAll(s => s.Status == Status.Active, new[] { "Bikes" });
        return View("../Dashboard/Stations", new StationListViewModel(stations));
    }

    [HttpPost("/stations")]
    public IActionResult Create(StationViewModel station)
    {
        if (ModelState.IsValid)
        {
            _unitOfWork.Stations.Add(new Station()
            {
                Id = Guid.NewGuid().ToString(),
                Name = station.StationName,
                Capacity = station.StationCapacity,
                Status = station.Status,
                Location = new Point(30.6046026, 30.9990875) { SRID = 4326 }
            });
            _unitOfWork.Complete();
        }

        return RedirectToAction(nameof(GetAll));
    }

    [HttpGet("/stations/{id}")]
    public IActionResult GetById(string id)
    {
        var station = _unitOfWork.Stations.Find(s => s.Id == id, new[] { "Bikes" });
        return View("../Dashboard/StationDetails", new StationViewModel()
        {
            Id = station?.Id ?? string.Empty,
            StationName = station?.Name ?? string.Empty,
            StationCapacity = station?.Capacity ?? 0,
            Status = station?.Status ?? string.Empty,
            AvailableBikes = station?.Bikes.Count ?? 0,
            Location = station?.Location
        });
    }

    [HttpPost("/stations/update")]
    public IActionResult Update(StationViewModel station)
    {
        if (ModelState.IsValid)
        {
            _unitOfWork.Stations.Update(new Station()
            {
                Id = station.Id,
                Name = station.StationName,
                Capacity = station.StationCapacity,
                Status = station.Status,
                Location = new Point(30.6046026, 30.9990875) { SRID = 4326 }
            });
            _unitOfWork.Complete();
        }

        return RedirectToAction(nameof(GetAll));
    }
}

WheelWander/Views/Shared/_Footer.cshtml
<footer class="main-footer">
    <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
        <b>Version</b> 3.2.0
    </div>

    <!-- REQUIRED SCRIPTS -->

    <!-- jQuery -->
    <script src="~/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE -->
    <script src="~/dist/js/adminlte.js"></script>

    <!-- OPTIONAL SCRIPTS -->
    <script src="~/plugins/chart.js/Chart.min.js"></script>
    <script src="~/dist/js/pages/dashboard3.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
</footer>

WheelWander/Views/Shared/_Header.cshtml
<header>
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
    <!-- IonIcons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/dist/css/adminlte.min.css">
</header>

WheelWander/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    
    <title>Dashboard</title>

    <!-- Styles -->
    <style>
        td {
            word-break: break-all;
        }

    </style>
</head>
<body>

<!-- Header -->
<!-- Include the header partial -->
<partial name="_Header" />

<!-- Navbar -->
<!-- Include the navbar partial -->
<partial name="_TopNavigation" />

<!-- Left Sidebar -->
<!-- Include the left-sidebar partial -->
<partial name="_MainNavigation" />

<!-- Content Wrapper. Contains page content -->
<section class="content">
    @RenderBody()
</section>

<footer>
    <!-- Include the footer partial -->
    <partial name="_Footer" />
</footer>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WheelWander/Views/Shared/_MainNavigation.cshtml
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="/dashboard/index" class="brand-link">
        <img src="~/dist/img/bike.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
             style="background:white">
        <span class="brand-text font-weight-light">Wheel Wander</span>
    </a>
    @{
        var action = this.ViewContext.RouteData.Values["action"] as string;
    }
    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                with font-awesome or any other icon font library -->
                <li class="nav-item">
                    <a asp-controller="Dashboard" asp-action="Index" class="nav-link @(action == "Index" ? "active" : "")">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                            Dashboard
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a asp-controller="Dashboard" asp-action="Users" class="nav-link @(action == "Users" ? "active" : "")">
                        <i class="nav-icon fa fa-users"></i>
                        <p>
                            Users
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a asp-controller="Dashboard" asp-action="Rentals" class="nav-link @(action == "Rentals" ? "active" : "")">
                        <i class="nav-icon fas fa-unlock"></i>
                        <p>
                            Rentals
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a asp-controller="Bikes" asp-action="List" class="nav-link @(action == "List" ? "active" : "")">
                        <i class="nav-icon fas fa-bicycle"></i>
                        <p>
                            Bikes
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a asp-controller="Stations" asp-action="GetAll" class="nav-link @(action == "GetAll" ? "active" : "")">
                        <i class="nav-icon fas fa-subway"></i>
                        <p>
                            Stations
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-exclamation-circle"></i>
                        <p>
                            Reported Problems
                            <span class="right badge badge-danger">3</span>
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-credit-card"></i>
                        <p>
                            Memberships
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-cog"></i>
                        <p>
                            Settings
                        </p>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>

WheelWander/Views/Shared/_TopNavigation.cshtml
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Navbar Search -->
        <li class="nav-item">
            <a class="nav-link" data-widget="navbar-search" href="#" role="button">
                <i class="fas fa-search"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                <i class="fas fa-expand-arrows-alt"></i>
            </a>
        </li>
    </ul>
    <partial name="_LoginPartial"/>
</nav>
<!-- /.navbar -->